spring:
  application:
    name: eureka-registry
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
server:
  port: 8761
---
spring:
  profiles: docker
  application:
    name: eureka-registry
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
server:
  port: 8761
 